server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: mika
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

liquibase:
  enabled: true
  change-log: db/changelog/db.changelog-master.yaml
  defaultSchema: public
